#!/usr/bin/env python3
"""
Reviewer-2 support-sensitivity check for TR-2026-412.R2.

Purpose
-------
The published/revision-1 analysis varied prior *scale* while retaining the
same lower support beta1 > 0.5. Reviewer 2 correctly noted that this does
not test sensitivity to the support restriction itself.

This script therefore repeats the primary PICM-L Bayesian fit twice:
  1. baseline support: beta1 > 0.5
  2. relaxed support:  beta1 > 0

All other prior hyperparameters, likelihood terms, MCMC controls, seeds,
and data are unchanged from optocoupler_thermal_reliability_study_pubrev_v5.py.

Outputs
-------
tables/table_beta1_support_sensitivity.csv
tables/table_beta1_support_sensitivity_diagnostics.csv
"""

from pathlib import Path
import numpy as np
import pandas as pd

import optocoupler_thermal_reliability_study_pubrev_v5 as core


REPO_ROOT = Path(__file__).resolve().parent.parent
TABLE_DIR = REPO_ROOT / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)


def b10_draws(samples: np.ndarray, delta_t: float) -> np.ndarray:
    """Posterior draws of Weibull B10 life in cycles at the requested DeltaT."""
    k = samples[:, 0]
    beta1 = samples[:, 1]
    beta0 = samples[:, 2]
    eta = np.exp(beta0 - beta1 * np.log(float(delta_t)))
    return eta * ((-np.log(0.9)) ** (1.0 / k))


def run_setting(data, mle_theta: np.ndarray, cfg: dict):
    """Run the same primary 3-chain adaptive Metropolis calculation as v5."""
    starts = core.make_picm_l_mcmc_starts(mle_theta, prior_cfg=cfg)
    fit = core.run_adaptive_mh_picm_l(
        data=data,
        starts=starts,
        seeds=core.SEED_MCMC,
        burnin=core.MCMC_BURNIN,
        keep=core.MCMC_KEEP,
        adapt_block=core.MCMC_ADAPT_BLOCK,
        prior_cfg=cfg,
    )
    chains = np.asarray(fit["chains"], dtype=float)
    samples = chains.reshape(-1, chains.shape[-1])
    rhat = core.compute_rhat(chains)
    ess = np.array(
        [core.effective_sample_size(chains[:, :, j]) for j in range(chains.shape[2])],
        dtype=float,
    )
    return fit, chains, samples, rhat, ess


def metric_summary(samples: np.ndarray, metric: str, delta_t: float | None = None):
    """Return median and 95% equal-tailed interval for beta1 or a B10 quantity."""
    if metric == "beta1":
        x = samples[:, 1]
    elif metric == "B10":
        if delta_t is None:
            raise ValueError("delta_t is required for B10")
        x = b10_draws(samples, delta_t)
    else:
        raise ValueError(f"Unsupported metric: {metric}")
    q025, q50, q975 = np.quantile(x, [0.025, 0.50, 0.975])
    return float(q50), float(q025), float(q975)


def main():
    # Canonical unit-level dataset and exact cycles = hours / 3.
    df, _source, _csv_path = core.load_input_dataset(
        core.INPUT_CSV,
        core.CYCLE_TIME_HOURS,
    )
    core.validate_dataset(
        df,
        cycle_time_hours=core.CYCLE_TIME_HOURS,
        enforce_real_failure_pattern=core.ENFORCE_REAL_FAILURE_PATTERN,
        pattern_mismatch_is_error=core.REAL_PATTERN_MISMATCH_IS_ERROR,
    )
    data = core.prepare_data(df)

    # Recompute the MLE so MCMC starts are generated by the same v5 workflow.
    mle_fit = core.fit_picm_l_mle(
        data=data,
        n_starts=core.N_OPT_STARTS_MAIN,
        seed=core.SEED_OPT,
    )
    mle_theta = np.asarray(mle_fit["theta"], dtype=float)

    baseline_cfg = core.get_prior_config(core.BASELINE_PRIOR_KEY)
    relaxed_cfg = dict(baseline_cfg)
    relaxed_cfg["beta1_trunc_lower"] = 0.0

    baseline_fit, baseline_chains, baseline_samples, baseline_rhat, baseline_ess = run_setting(
        data, mle_theta, baseline_cfg
    )
    relaxed_fit, relaxed_chains, relaxed_samples, relaxed_rhat, relaxed_ess = run_setting(
        data, mle_theta, relaxed_cfg
    )

    # Regression check against the archived baseline table generated by v5.
    archived_beta1_median = 2.458146144501661
    beta1_baseline_median = float(np.median(baseline_samples[:, 1]))
    if abs(beta1_baseline_median - archived_beta1_median) > 1e-6:
        raise RuntimeError(
            "Baseline reproducibility check failed: "
            f"{beta1_baseline_median:.12f} vs archived {archived_beta1_median:.12f}"
        )

    settings = {
        "baseline_beta1_gt_0p5": {
            "lower": 0.5,
            "samples": baseline_samples,
            "fit": baseline_fit,
            "rhat": baseline_rhat,
            "ess": baseline_ess,
        },
        "support_relaxed_beta1_gt_0": {
            "lower": 0.0,
            "samples": relaxed_samples,
            "fit": relaxed_fit,
            "rhat": relaxed_rhat,
            "ess": relaxed_ess,
        },
    }

    baseline_reference = {}
    for metric, dt in [("beta1", None), ("B10", 20.0), ("B10", 25.0), ("B10", 35.0)]:
        key = "beta1" if metric == "beta1" else f"B10_{int(dt)}C_cycles"
        baseline_reference[key] = metric_summary(baseline_samples, metric, dt)

    rows = []
    for setting_name, obj in settings.items():
        samples = obj["samples"]
        for metric, dt in [("beta1", None), ("B10", 20.0), ("B10", 25.0), ("B10", 35.0)]:
            metric_name = "beta1" if metric == "beta1" else f"B10_{int(dt)}C_cycles"
            median, lo, hi = metric_summary(samples, metric, dt)
            base_median = baseline_reference[metric_name][0]
            shift = 100.0 * (median / base_median - 1.0)
            rows.append(
                {
                    "setting": setting_name,
                    "beta1_trunc_lower": obj["lower"],
                    "metric": metric_name,
                    "median": median,
                    "eti_2.5": lo,
                    "eti_97.5": hi,
                    "relative_median_shift_percent_vs_baseline": shift,
                }
            )

    summary = pd.DataFrame(rows)
    summary.to_csv(TABLE_DIR / "table_beta1_support_sensitivity.csv", index=False)

    diag_rows = []
    parameter_names = ["k", "beta1", "beta0"]
    for setting_name, obj in settings.items():
        for chain_no, acc in enumerate(obj["fit"]["accept_rates"], start=1):
            diag_rows.append(
                {
                    "setting": setting_name,
                    "diagnostic": "chain_acceptance",
                    "parameter_or_chain": f"chain_{chain_no}",
                    "value": float(acc),
                }
            )
        for j, name in enumerate(parameter_names):
            diag_rows.append(
                {
                    "setting": setting_name,
                    "diagnostic": "rhat",
                    "parameter_or_chain": name,
                    "value": float(obj["rhat"][j]),
                }
            )
            diag_rows.append(
                {
                    "setting": setting_name,
                    "diagnostic": "ess",
                    "parameter_or_chain": name,
                    "value": float(obj["ess"][j]),
                }
            )

    # Direct diagnostic requested by the review logic: how much relaxed posterior
    # mass actually enters the old excluded region beta1 <= 0.5?
    relaxed_below_old_bound = float(np.mean(relaxed_samples[:, 1] <= 0.5))
    diag_rows.append(
        {
            "setting": "support_relaxed_beta1_gt_0",
            "diagnostic": "posterior_fraction_beta1_le_0p5",
            "parameter_or_chain": "beta1",
            "value": relaxed_below_old_bound,
        }
    )

    pd.DataFrame(diag_rows).to_csv(
        TABLE_DIR / "table_beta1_support_sensitivity_diagnostics.csv",
        index=False,
    )

    print("\nReviewer-2 support-sensitivity check")
    print("====================================")
    print(summary.to_string(index=False))
    print("\nRelaxed-support diagnostics:")
    print("acceptance rates:", relaxed_fit["accept_rates"])
    print("R-hat [k, beta1, beta0]:", relaxed_rhat)
    print("ESS   [k, beta1, beta0]:", relaxed_ess)
    print("fraction of relaxed posterior draws with beta1 <= 0.5:", relaxed_below_old_bound)


if __name__ == "__main__":
    main()
